"""Generate HTML dashboard from daily log data.

Run after daily_update.py to create docs/dashboard.html
"""
import sys; sys.path.insert(0, "src")

import json
import pandas as pd
from pathlib import Path
from datetime import datetime

from nowcasting_toolbox.eval.metrics import compute_mae, compute_fda, compute_rmse

# Load daily log
log_path = Path("docs/daily_log.csv")
if not log_path.exists():
    print("No daily_log.csv found. Run daily_update.py first.")
    sys.exit(1)

log = pd.read_csv(log_path)
latest = log.iloc[-1]

# Load leaderboard if exists
lb_path = Path("docs/leaderboard.csv")
leaderboard = []
if lb_path.exists():
    lb = pd.read_csv(lb_path)
    for _, row in lb.iterrows():
        leaderboard.append({
            "model": row["model"],
            "mae": round(row["MAE (pp)"], 3),
            "rmse": round(row["RMSE (pp)"], 3),
            "fda": round(row["FDA (%)"], 1),
            "n": int(row["N"]),
            "latest": round(float(row.get("last_nowcast", 0)), 1),
        })

# Build data object
data = {
    "lastUpdated": str(latest["date"]),
    "latestActual": {
        "quarter": "Q1 2026",
        "yoy": 5.4,
    },
    "nowcast": {
        "quarter": "Q2 2026",
        "dfm": round(float(latest.get("dfm_yoy", 0)), 1) if pd.notna(latest.get("dfm_yoy")) else None,
        "bvar": round(float(latest.get("bvar_yoy", 0)), 1) if pd.notna(latest.get("bvar_yoy")) else None,
        "ensemble": round(float(latest.get("ensemble_yoy", 0)), 1) if pd.notna(latest.get("ensemble_yoy")) else None,
    },
    "backcast": {},
    "components": {},
    "sectors": {},
    "leaderboard": leaderboard,
    "recent": [],
}

# Backcast errors
actual_yoy = 5.4
for model in ["dfm", "bvar", "ensemble"]:
    est = data["nowcast"].get(model)
    data["backcast"][model] = {
        "estimate": est,
        "error": round(abs(est - actual_yoy), 1) if est else None,
    }

# Components
comp_map = {
    "consumption": ("consumption", "consumption_actual"),
    "investment": ("investment", "investment_actual"),
    "government": ("government", "government_actual"),
    "exports": ("exports_comp", "exports_comp_actual"),
    "imports": ("imports_comp", "imports_comp_actual"),
}
for key, (bvar_col, actual_col) in comp_map.items():
    bvar_val = latest.get(bvar_col)
    actual_val = latest.get(actual_col)
    data["components"][key] = {
        "bvar": round(float(bvar_val), 1) if pd.notna(bvar_val) else None,
        "actual": round(float(actual_val), 1) if pd.notna(actual_val) else None,
        "error": round(abs(float(bvar_val) - float(actual_val)), 1) if pd.notna(bvar_val) and pd.notna(actual_val) else None,
    }

# Sectors (hardcoded from latest DOSM data)
data["sectors"] = {
    "agriculture": 2.6,
    "mining": -2.1,
    "manufacturing": 5.9,
    "construction": 7.7,
    "services": 5.6,
}

# Recent nowcasts
for _, row in log.tail(30).iterrows():
    recent = {"date": str(row["date"])}
    for m in ["dfm", "bvar", "beq", "ensemble"]:
        v = row.get(m)
        recent[m] = round(float(v), 1) if pd.notna(v) else None
    actual_v = row.get("actual_gdp_pct")
    recent["actual"] = round(float(actual_v), 1) if pd.notna(actual_v) else None
    data["recent"].append(recent)

# Write data.json for the HTML to load
data_path = Path("docs/data.json")
data_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"Data written to {data_path}")

# Now update the HTML to load from data.json
html_path = Path("docs/dashboard.html")
if html_path.exists():
    html = html_path.read_text(encoding="utf-8")
    
    # Replace the script section to load from data.json
    old_script = """    <script>
        // This script would be populated with actual data from the daily update
        // For now, showing placeholder structure
        
        // Example data (would be injected by daily_update.py)
        const data = {"""
    
    new_script = """    <script>
        // Load data from data.json (generated by generate_dashboard.py)
        let data;
        fetch('data.json')
            .then(r => r.json())
            .then(d => { data = d; populateDashboard(data); })
            .catch(e => console.error('Failed to load data:', e));
        
        function populateDashboard(data) {"""
    
    html = html.replace(old_script, new_script)
    
    # Close the function and script properly
    html = html.replace(
        "    </script>",
        """
        }
    </script>"""
    )
    
    html_path.write_text(html, encoding="utf-8")
    print(f"Dashboard updated at {html_path}")
